version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
     - POSTGRES_USER=silva
     - POSTGRES_PASSWORD=12345
     - POSTGRES_DB=store
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
